export interface ProductItem {
  id?: number
  title: string
  slug: string
  category: 'Pet Food & Treats' | 'Accessories & Collars' | 'Vitamins & Healthcare' | 'Toys & Play' | 'Grooming & Hygiene'
  petType: 'Dog' | 'Cat' | 'Bird' | 'Fish' | 'Small Pet' | 'All Pets'
  price: number
  originalPrice: number
  stock: number
  rating: number
  reviewsCount: number
  sku: string
  imageUrl: string
  excerpt: string
  description: string
  keyBenefits: string[]
  ingredients: string
  usageGuide: string
  weightSize: string
  brand: string
  isFeatured?: boolean
}

export const ALL_25_PRODUCTS: ProductItem[] = [
  // ─── 1. Pet Food & Treats ───
  {
    title: 'Grain-Free Salmon & Sweet Potato Dry Dog Kibble',
    slug: 'grain-free-salmon-sweet-potato-dog-kibble',
    category: 'Pet Food & Treats',
    petType: 'Dog',
    price: 1450,
    originalPrice: 1690,
    stock: 28,
    rating: 4.9,
    reviewsCount: 38,
    sku: 'PT-FOOD-001',
    // Dog eating from bowl / dog food kibble
    imageUrl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Rich wild-caught salmon and antioxidant-packed sweet potatoes formulated for adult canines with sensitive stomachs.',
    description: 'Our Grain-Free Salmon & Sweet Potato Recipe is packed with high-protein real salmon meal, digestible complex carbohydrates, and essential omega fatty acids to keep your pup energetic and sporting a lustrous coat. Free from artificial fillers, corn, wheat, or poultry by-products.',
    keyBenefits: [
      'Fresh debone salmon is the #1 single source ingredient',
      'Naturally rich in EPA and DHA for brain and heart health',
      'Digestible fiber from wholesome pumpkin and sweet potatoes',
      'Fortified with live probiotics for optimal nutrient absorption',
    ],
    ingredients: 'Deboned Salmon, Salmon Meal, Sweet Potatoes, Green Peas, Canola Oil, Flaxseed, Natural Flavors, Blueberries, Cranberries, Vitamins (A, D3, E, B12), Minerals (Zinc, Iron, Manganese).',
    usageGuide: 'Feed 1.5 to 2.5 cups daily based on canine body weight (10-25kg). Always ensure clean fresh water is accessible.',
    weightSize: '3.0 kg Bag',
    brand: 'Paws & Tails Heritage Diet',
    isFeatured: true,
  },
  {
    title: 'Ocean Whitefish & Tuna Gourmet Cat Wet Pouch (Box of 12)',
    slug: 'ocean-whitefish-tuna-wet-cat-pouch-12x',
    category: 'Pet Food & Treats',
    petType: 'Cat',
    price: 680,
    originalPrice: 790,
    stock: 45,
    rating: 5.0,
    reviewsCount: 64,
    sku: 'PT-FOOD-002',
    // Cat eating wet food / cat food pouch
    imageUrl: 'https://images.unsplash.com/photo-1611471571826-b3d11e88d49b?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Tender flake morsels simmered in savoury seafood broth to satisfy finicky feline tastebuds and promote urinary hydration.',
    description: 'Crafted with sustainably caught wild whitefish and skipjack tuna fillets in a delicate savory gravy. Each single-serve pouch provides complete and balanced moisture-rich dining that supports kidney and urinary tract health.',
    keyBenefits: [
      'High moisture content (82%) keeps cats hydrated daily',
      'Zero grain, carrageenan, or artificial flavor enhancers',
      'Packed with essential taurine for sharp vision and heart health',
      'Convenient easy-tear recyclable pouches',
    ],
    ingredients: 'Wild Ocean Whitefish, Yellowfin Tuna, Fish Broth, Sunflower Oil, Tapioca Starch, Taurine, Vitamin E Supplement, Choline Chloride, Zinc Sulfate.',
    usageGuide: 'Feed 2 to 3 pouches per 4kg of adult cat weight per day. Refrigerate unused portion up to 48 hours.',
    weightSize: '12 x 85g Pouches',
    brand: 'Purrfect Delights',
    isFeatured: true,
  },
  {
    title: 'FruitBlend Premium Pellets for Parrots & Conures',
    slug: 'fruitblend-premium-pellets-parrots',
    category: 'Pet Food & Treats',
    petType: 'Bird',
    price: 520,
    originalPrice: 590,
    stock: 32,
    rating: 4.8,
    reviewsCount: 22,
    sku: 'PT-FOOD-003',
    // Colorful parrot / bird eating
    imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Colorfully shaped extruded fruit-essence pellets packed with essential vitamins to prevent seed malnutrition.',
    description: 'Formulated by avian nutritionists to provide precise daily nutrition for medium and large pet birds. Eliminates the selective eating habits caused by seed diets and ensures consistent vitamin and mineral uptake.',
    keyBenefits: [
      'Natural fruit flavors (banana, orange, apple, grape)',
      'Prevents vitamin A and calcium deficiencies common in cage birds',
      'No seed hulls or messy cage floor waste',
      'Balanced calcium-to-phosphorus ratio for bone density',
    ],
    ingredients: 'Ground Corn, Soybean Meal, Ground Wheat, Wheat Germ Meal, Sugar, Vegetable Oil, Natural Fruit Aromas, Calcium Carbonate, Dicalcium Phosphate, Vitamin A Supplement.',
    usageGuide: 'Feed 1/4 to 1/2 cup daily per bird. Introduce gradually over a 14-day transition period.',
    weightSize: '900g Resealable Bag',
    brand: 'Avian Elite Nutrition',
    isFeatured: false,
  },
  {
    title: 'Micro Pellets Tropical Fish Daily Sinking Nutrition',
    slug: 'micro-pellets-tropical-fish-nutrition',
    category: 'Pet Food & Treats',
    petType: 'Fish',
    price: 340,
    originalPrice: 395,
    stock: 60,
    rating: 4.9,
    reviewsCount: 41,
    sku: 'PT-FOOD-004',
    // Tropical fish in aquarium
    imageUrl: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Slow-sinking micro bites infused with marine spirulina and astaxanthin for vibrant neon and tetra coloring.',
    description: 'Specially engineered for tetras, barbs, guppies, and small community tropical species with small mouths. Will not cloud aquarium water and provides immune-boosting bioactive peptides.',
    keyBenefits: [
      'Spirulina and krill meal naturally amplify tropical scales',
      'Slow-sinking behavior matches natural middle-stratum feeding',
      'Bio-formulated enzymes reduce ammonia waste output',
      'Contains stabilized Vitamin C for stress reduction',
    ],
    ingredients: 'Fish Meal, Krill Meal, Wheat Flour, Spirulina, Dried Brewers Yeast, Fish Oil, Astaxanthin, Vitamin Premix, Garlic Extract.',
    usageGuide: 'Feed 2 to 3 times daily only as much food as fish can consume within 2 minutes. Remove excess food promptly.',
    weightSize: '80g Dispenser Can',
    brand: 'AquaGlow Marine',
    isFeatured: false,
  },
  {
    title: 'Western Timothy Hay High-Fiber Grass for Rabbits & Guinea Pigs',
    slug: 'western-timothy-hay-high-fiber-grass',
    category: 'Pet Food & Treats',
    petType: 'Small Pet',
    price: 495,
    originalPrice: 550,
    stock: 35,
    rating: 5.0,
    reviewsCount: 29,
    sku: 'PT-FOOD-005',
    // Rabbit eating hay / guinea pig with hay
    imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Sun-cured 1st cut sweet timothy grass with long fibers that promote dental wear and healthy gut motility.',
    description: 'Hand-sorted and dust-extracted long-stem western timothy hay. Essential for herbivorous small animals including rabbits, guinea pigs, and chinchillas to naturally grind continually growing incisors and prevent GI stasis.',
    keyBenefits: [
      'High beneficial crude fiber (32%) and low calcium',
      'Aromatic sweet smell encourages natural foraging behavior',
      'Double compressed and vacuum packed to prevent mildew',
      'Zero artificial preservatives or pesticides',
    ],
    ingredients: '100% Sun-Cured Western Timothy Grass Hay.',
    usageGuide: 'Provide unlimited access at all times. Fresh hay should make up roughly 80% of your small pet\'s daily diet.',
    weightSize: '1.2 kg Fresh-Bale',
    brand: 'MeadowHarvest Pet',
    isFeatured: true,
  },

  // ─── 2. Accessories & Collars ───
  {
    title: 'Reflective Tactical No-Pull Dog Harness with Breathable Mesh',
    slug: 'reflective-no-pull-dog-harness-breathable',
    category: 'Accessories & Collars',
    petType: 'Dog',
    price: 590,
    originalPrice: 750,
    stock: 24,
    rating: 4.9,
    reviewsCount: 52,
    sku: 'PT-ACC-006',
    // Dog wearing harness on walk
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Ergonomic dual-clip chest harness with padded air-cushion mesh and 3M night-vision reflective striping.',
    description: 'Designed to eliminate choking hazards and guide strong pullers gently. Features a front chest D-ring for leash training and a reinforced back handle for instant control during crosswalks or dog park interactions.',
    keyBenefits: [
      'Front clip discourages leash pulling without neck strain',
      '3M Scotchlite reflective piping for safe twilight and dawn walks',
      '4 adjustable sliders create a tailored anti-slip fit',
      'Heavy-duty alloy D-rings tested to withstand 180kg tension',
    ],
    ingredients: 'Military-grade 1000D Oxford Nylon, Breathable Foam Mesh, Zinc Alloy Rings, Duraflex Quick-Release Buckles.',
    usageGuide: 'Unbuckle chest straps, slip neck opening over dog\'s head, secure side buckles, and adjust fit to allow 2 fingers beneath webbing.',
    weightSize: 'Adjustable Medium (Chest 52-70cm)',
    brand: 'TrailK9 Performance',
    isFeatured: true,
  },
  {
    title: 'Breakaway Safety Velvet Cat Collar with Golden Bell',
    slug: 'breakaway-safety-velvet-cat-collar-bell',
    category: 'Accessories & Collars',
    petType: 'Cat',
    price: 240,
    originalPrice: 320,
    stock: 50,
    rating: 4.8,
    reviewsCount: 33,
    sku: 'PT-ACC-007',
    // Cat wearing collar close-up
    imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Plush baby-blue velvet collar featuring an automatic quick-release buckle to prevent snagging injuries.',
    description: 'Super soft on feline neck fur to avoid matting and irritation. The precision breakaway clip snaps open smoothly if your curious cat gets snagged on branches, window blinds, or furniture.',
    keyBenefits: [
      'Quick-release safety buckle triggers at 2.5kg force',
      'Detachable pleasant chime brass bell alerts nearby wildlife',
      'Ultra-soft plush velvet lining prevents chafing',
      'Adjustable neck strap fits kittens and adult cats alike',
    ],
    ingredients: 'Plush Micro-Velvet Fabric, Engineered ABS Breakaway Clasp, Brass Bell.',
    usageGuide: 'Adjust slider to fit cat neck snugly with enough space to slide 1-2 fingers easily underneath.',
    weightSize: 'Adjustable 18-30 cm',
    brand: 'Whiskers & Co.',
    isFeatured: false,
  },
  {
    title: 'Multi-Branch Natural Pepper Wood Bird Perch Stand',
    slug: 'multi-branch-natural-wood-bird-perch',
    category: 'Accessories & Collars',
    petType: 'Bird',
    price: 380,
    originalPrice: 450,
    stock: 19,
    rating: 4.7,
    reviewsCount: 16,
    sku: 'PT-ACC-008',
    // Bird perch / parrot on branch
    imageUrl: 'https://images.unsplash.com/photo-1522858547137-f1dcec554f55?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Rough-textured organic hardwood branch that naturally exercises feet muscles and trims bird talons.',
    description: 'Uniform plastic dowels can cause bumblefoot in pet birds. This wild pepperwood perch mimics outdoor forest branches with varied diameters, challenging foot grip and keeping pet claws trim.',
    keyBenefits: [
      'Varying branch thickness exercises bird foot tendons',
      'Organic untreated wood is 100% safe for chewing and preening',
      'Heavy-duty stainless steel wingnut mounts easily to any cage wire',
      'Supports cockatiels, lovebirds, conures, and budgies',
    ],
    ingredients: '100% Organic Pepperwood Hardwood, Stainless Steel Mounting Washer and Butterfly Wingnut.',
    usageGuide: 'Position inside cage wire at varying heights. Wipe clean with warm water and bird-safe cleaner.',
    weightSize: 'Length 28cm · Diameter 1.8-3.0cm',
    brand: 'Avian Habitat Essentials',
    isFeatured: false,
  },
  {
    title: 'Submersible Multi-Color LED Aquarium Bubble Wand',
    slug: 'submersible-led-aquarium-bubble-wand',
    category: 'Accessories & Collars',
    petType: 'Fish',
    price: 460,
    originalPrice: 580,
    stock: 22,
    rating: 4.9,
    reviewsCount: 27,
    sku: 'PT-ACC-009',
    // Colorful lit aquarium with bubbles
    imageUrl: 'https://images.unsplash.com/photo-1520301255226-bf5f144451c1?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Waterproof atmospheric LED strip and micro-porous aerating air stone that enriches dissolved oxygen.',
    description: 'Transform your aquarium into a mesmerizing illuminated water column. Micro-porous air stone generates shimmering bubble curtains that boost dissolved oxygen for lively and energetic fish.',
    keyBenefits: [
      'IP68 100% waterproof sealed silicone construction',
      'Energy efficient 12V low-voltage soft blue/cyan LED output',
      'Dual heavy-grip suction cups hold firmly to tank bottom',
      'Enhances dissolved oxygen while creating dramatic ambient effects',
    ],
    ingredients: 'Aerating Mineral Stone Core, Waterproof LED Array, Silicone Suction Bases, 1.5m Power Cord.',
    usageGuide: 'Connect to any standard 4mm aquarium air pump tube (air pump sold separately). Place on bottom gravel.',
    weightSize: '30cm Length (Tanks up to 50 Gallons)',
    brand: 'AquaGlow Marine',
    isFeatured: false,
  },
  {
    title: 'Silent Bearing Exercise Wheel for Hamsters & Mice',
    slug: 'silent-bearing-exercise-wheel-hamster',
    category: 'Accessories & Collars',
    petType: 'Small Pet',
    price: 390,
    originalPrice: 470,
    stock: 30,
    rating: 4.9,
    reviewsCount: 38,
    sku: 'PT-ACC-010',
    // Hamster running on wheel
    imageUrl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Whisper-quiet dual ball-bearing running wheel with solid running track preventing toe pinching.',
    description: 'Hamsters run up to 8 kilometers every night. This dual stainless steel bearing running disc glides silently without annoying squeaks, protecting both your pet\'s spine and your sleep.',
    keyBenefits: [
      'Silent dual-bearing mechanism operates under 15 decibels',
      'Flat solid running track eliminates tail and foot pinching',
      'Broad 21cm diameter prevents painful curvature of the spine',
      'Height adjustable acrylic pedestal stand',
    ],
    ingredients: 'Food-grade Shatterproof Acrylic, Precision Dual Steel Ball Bearings, Weighted Base Plate.',
    usageGuide: 'Place inside cage on flat bedding or bolt directly to cage bars using rear thumbscrew.',
    weightSize: '21cm Diameter (For Dwarfs & Syrian Hamsters)',
    brand: 'CritterJoy Gear',
    isFeatured: false,
  },

  // ─── 3. Vitamins & Healthcare ───
  {
    title: 'Pure Wild Alaskan Salmon Oil Coat & Joint Supplement (250ml)',
    slug: 'wild-alaskan-salmon-oil-supplement-250ml',
    category: 'Vitamins & Healthcare',
    petType: 'All Pets',
    price: 780,
    originalPrice: 890,
    stock: 40,
    rating: 5.0,
    reviewsCount: 71,
    sku: 'PT-VIT-011',
    // Salmon oil supplement bottle / fish oil
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Cold-pressed 100% natural fish oil rich in Omega-3, 6, and DHA for shiny coats, soft paws, and hip mobility.',
    description: 'Human-grade wild Alaskan salmon oil packed with natural astaxanthin and bioavailable fatty acids. Drizzle directly over dry or wet meals to transform itchy, dry skin into a radiant, velvety pet coat within 3 weeks.',
    keyBenefits: [
      'Noticeably reduces shedding, dandruff, and seasonal itching',
      'Soothes stiff hips and improves joint flexibility in older dogs',
      'Delicious natural fish flavor enhances appetite for picky eaters',
      'Pump dispenser prevents messy oil drips and oxidation',
    ],
    ingredients: '100% Cold-Pressed Wild Alaskan Salmon Oil, Natural Mixed Tocopherols (Vitamin E preservative).',
    usageGuide: '1 pump per 5kg pet weight daily mixed into food. Suitable for both dogs and cats of all life stages.',
    weightSize: '250ml Pump Bottle',
    brand: 'VetVitality Lab',
    isFeatured: true,
  },
  {
    title: 'Calci-Pet Daily Calcium + Vitamin D3 Chewable Tablets (100 Tabs)',
    slug: 'calci-pet-calcium-vitamin-d3-chews',
    category: 'Vitamins & Healthcare',
    petType: 'Dog',
    price: 450,
    originalPrice: 520,
    stock: 36,
    rating: 4.8,
    reviewsCount: 44,
    sku: 'PT-VIT-012',
    // Pet supplement / vitamin tablets
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Liver-flavored chewable mineral tablets supporting bone development in growing puppies and nursing dams.',
    description: 'Balanced calcium and phosphorus supplemented with Vitamin D3 to optimize mineral absorption. Formulated especially for large breed puppies during rapid bone development and aging dogs needing bone density support.',
    keyBenefits: [
      'Prevents rickets, eclampsia, and mineral deficiencies in dogs',
      'Delectable roasted poultry liver flavor treats like a candy treat',
      'Fortified with Magnesium and Vitamin C for joint cartilage health',
      'Manufactured in cGMP veterinary certified laboratory',
    ],
    ingredients: 'Calcium Carbonate, Dicalcium Phosphate, Vitamin D3 (Cholecalciferol), Magnesium Oxide, Hydrolyzed Poultry Liver, Brewers Yeast.',
    usageGuide: 'Give 1 tablet per 10kg body weight daily before meals. May be crumbled directly onto kibble.',
    weightSize: '100 Chewable Tablets',
    brand: 'VetVitality Lab',
    isFeatured: false,
  },
  {
    title: 'Hairball Relief & Digestive Prebiotic Malt Paste (100g)',
    slug: 'hairball-relief-digestive-malt-paste-100g',
    category: 'Vitamins & Healthcare',
    petType: 'Cat',
    price: 420,
    originalPrice: 480,
    stock: 48,
    rating: 4.9,
    reviewsCount: 39,
    sku: 'PT-VIT-013',
    // Cat grooming / health supplement
    imageUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Soothing malt extract paste that binds swallowed grooming hair and gently passes it through the digestive tract.',
    description: 'Eliminate traumatic gagging and hairball vomiting. Combines golden malt extract with prebiotic dietary fiber to lubricate the gastrointestinal tract and support balanced gut flora in indoor grooming felines.',
    keyBenefits: [
      'Gently dissolves swallowed fur balls without uncomfortable vomiting',
      'Enriched with prebiotic MOS to nurture beneficial gut bacteria',
      'Appealing malt and cheese taste cats lick directly from your finger',
      'Contains zero added sugars or synthetic laxatives',
    ],
    ingredients: 'Malt Extract (60%), Vegetable Oils, Apple Cellulose Fiber, Prebiotic MOS (Mannan-Oligosaccharides), Lecithin.',
    usageGuide: 'Squeeze 3-4cm paste daily onto paw or finger. Use twice weekly for regular maintenance.',
    weightSize: '100g Squeeze Tube',
    brand: 'Purrfect Delights',
    isFeatured: true,
  },
  {
    title: 'Avian Soluble Multivitamin & Feather Growth Drops (50ml)',
    slug: 'avian-soluble-multivitamin-feather-drops',
    category: 'Vitamins & Healthcare',
    petType: 'Bird',
    price: 295,
    originalPrice: 350,
    stock: 25,
    rating: 4.7,
    reviewsCount: 19,
    sku: 'PT-VIT-014',
    // Bright parrot / bird healthcare
    imageUrl: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Water-soluble bird tonic formulated with 14 essential vitamins and amino acids for molt recovery and singing vigor.',
    description: 'During seasonal molting periods, birds need concentrated amino acids and sulfur to regenerate glossy, strong plumage. These concentrated drops dissolve readily into drinking water to protect against lethargy.',
    keyBenefits: [
      'Accelerates healthy feather molting and restores vibrant coloration',
      'Fortifies immunity during climate transitions and cage transfers',
      'Contains Biotin, Choline, and Vitamin B-Complex for active vocalization',
      'Precision dropper cap ensures exact dilution dosing',
    ],
    ingredients: 'Vitamins A, B1, B2, B6, B12, C, D3, E, K3, Biotin, Folic Acid, Lysine, Methionine in Purified Aqueous Base.',
    usageGuide: 'Add 4 to 6 drops per 50ml of fresh drinking water. Prepare fresh solution daily.',
    weightSize: '50ml Dropper Bottle',
    brand: 'Avian Elite Nutrition',
    isFeatured: false,
  },
  {
    title: 'AquaSafe Water Conditioner & Fast Dechlorinator (250ml)',
    slug: 'aquasafe-water-conditioner-dechlorinator',
    category: 'Vitamins & Healthcare',
    petType: 'Fish',
    price: 380,
    originalPrice: 440,
    stock: 55,
    rating: 5.0,
    reviewsCount: 62,
    sku: 'PT-VIT-015',
    // Clear aquarium water / fish tank
    imageUrl: 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Instant action tap water detoxifier that neutralizes chlorine, chloramines, and binds toxic heavy metals in seconds.',
    description: 'Tap water contains sterilizing chlorine that harms delicate fish gills. AquaSafe instantly detoxifies municipal tap water and deposits a protective colloids mucus film over freshwater and marine fish scales.',
    keyBenefits: [
      'Instantly removes lethal chlorine and toxic chloramines',
      'Binds heavy metal ions like copper, lead, and zinc safely',
      'BioExtract formula coats scales and gills to prevent bacterial infections',
      'Essential for water changes, setting up new tanks, and fish transport',
    ],
    ingredients: 'Sodium Thiosulfate, EDTA Metal Chelating Complex, Organic Colloid Protective Polymers, Sea Kelp Bio-Extract.',
    usageGuide: 'Add 5ml per 10 gallons (38L) of new tap water before introducing to the aquarium.',
    weightSize: '250ml Treats 500 Gallons',
    brand: 'AquaGlow Marine',
    isFeatured: false,
  },

  // ─── 4. Toys & Play ───
  {
    title: 'Indestructible Natural Rubber Treat-Dispensing Chew Bone',
    slug: 'indestructible-rubber-treat-dispenser-bone',
    category: 'Toys & Play',
    petType: 'Dog',
    price: 380,
    originalPrice: 480,
    stock: 34,
    rating: 4.9,
    reviewsCount: 57,
    sku: 'PT-TOY-016',
    // Dog playing with chew toy / rubber bone
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Ultra-durable natural rubber dog bone with textured dental nubs and treat-stuffing chambers to beat boredom.',
    description: 'Designed for aggressive chewers who destroy plush toys in minutes. The hollow center can be stuffed with peanut butter, kibble, or treats to stimulate your dog\'s brain and clean teeth simultaneously.',
    keyBenefits: [
      '100% puncture-resistant food-safe natural vulcanized rubber',
      'Geometric dental nubs massage gums and scrape away plaque',
      'Ergonomic bone shape encourages paw-holding while chewing',
      'Freezer and top-rack dishwasher safe for easy sanitizing',
    ],
    ingredients: 'Non-toxic Natural Vulcanized Tree Rubber, Mild Vanilla Scenting.',
    usageGuide: 'Fill hollow chambers with kibble or healthy treats. Hand wash or run on top dishwasher rack.',
    weightSize: '19cm Large (For Dogs 10-35kg)',
    brand: 'TrailK9 Performance',
    isFeatured: true,
  },
  {
    title: 'Automatic Smart Laser & Feather Teaser Rotating Cat Ball',
    slug: 'automatic-smart-laser-feather-rotating-cat-ball',
    category: 'Toys & Play',
    petType: 'Cat',
    price: 690,
    originalPrice: 850,
    stock: 26,
    rating: 4.8,
    reviewsCount: 47,
    sku: 'PT-TOY-017',
    // Cat playing with toy / feather wand
    imageUrl: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80',
    excerpt: 'USB-rechargeable self-rolling robotic ball with erratic 360° motion, LED glow, and bird feather attachment.',
    description: 'Keep your indoor cat fit and mentally engaged while you work. Built-in smart sensors automatically navigate around walls, rugs, and furniture, reversing direction randomly to trigger feline predatory chase instincts.',
    keyBenefits: [
      'Intelligent obstacle detection avoids getting stuck under couches',
      'Auto shut-off timer rests every 15 minutes to avoid over-exhaustion',
      'Rechargeable 500mAh lithium battery via standard USB-C cable',
      'Includes interchangeable bell, feather, and ribbon teasers',
    ],
    ingredients: 'Durable Impact-Resistant ABS Shell, Soft Silicone Tires, Natural Feathers, USB-C Circuit Board.',
    usageGuide: 'Press power button to initiate self-rolling. One 60-minute charge powers 4 hours of playtime.',
    weightSize: '6.4cm Diameter Ball',
    brand: 'Purrfect Delights',
    isFeatured: true,
  },
  {
    title: 'Foraging Shredder Bell & Rattan Ball Chew Cluster',
    slug: 'foraging-shredder-bell-rattan-chew-cluster',
    category: 'Toys & Play',
    petType: 'Bird',
    price: 260,
    originalPrice: 320,
    stock: 40,
    rating: 4.7,
    reviewsCount: 18,
    sku: 'PT-TOY-018',
    // Colorful parrot with toy
    imageUrl: 'https://images.unsplash.com/photo-1559715541-5daf8a0296d0?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Hanging cage puzzle loaded with colorful crinkle paper, woven rattan balls, and ringing bells.',
    description: 'Parrots are naturally inquisitive and need destructive foraging activities to prevent stress-induced feather plucking. This hanging cluster gives them safe paper to shred and rattan balls to unweave.',
    keyBenefits: [
      'Satisfies innate avian foraging, shredding, and preening urges',
      'Dyed with 100% pet-safe non-toxic edible food coloring',
      'Quick-link steel clip attaches securely to top cage bars',
      'Helps prevent boredom-induced screeching and cage stress',
    ],
    ingredients: 'Natural Woven Rattan Balls, Crinkle Paper Strips, Wood Beads, Nickeled Brass Bell, Steel Quick-Link.',
    usageGuide: 'Hang in upper middle section of cage. Hide sunflower seeds or nuts inside rattan balls for foraging fun.',
    weightSize: 'Height 25cm · Width 10cm',
    brand: 'Avian Habitat Essentials',
    isFeatured: false,
  },
  {
    title: 'Ancient Shipwreck Resin Coral Reef Aquarium Hideout',
    slug: 'ancient-shipwreck-resin-aquarium-hideout',
    category: 'Toys & Play',
    petType: 'Fish',
    price: 520,
    originalPrice: 650,
    stock: 18,
    rating: 4.9,
    reviewsCount: 31,
    sku: 'PT-TOY-019',
    // Aquarium decorations / coral reef
    imageUrl: 'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Detailed underwater galleon ruin with swim-through portals and cavern hideaways for shy fish and shrimp.',
    description: 'Provides crucial territory dividers and peaceful shelter caves for territorial cichlids, nocturnal catfish, and breeding aquarium shrimp. Hand-painted with non-toxic waterproof pigments.',
    keyBenefits: [
      'Multiple hollow chambers create calm stress-relief hideaways',
      'Does not alter aquarium water pH, GH, or chemical parameters',
      'Weighted base ensures it stays stable in sand or gravel beds',
      'Smooth hand-polished portal edges prevent fish fin tears',
    ],
    ingredients: 'Eco-friendly Polyresin, Non-toxic Color Pigments (Freshwater and Marine safe).',
    usageGuide: 'Rinse with cool water before placing into aquarium. No soap or detergent needed.',
    weightSize: '24cm Length × 13cm Height × 9cm Width',
    brand: 'AquaGlow Marine',
    isFeatured: false,
  },
  {
    title: 'Crinkle Play Tunnel & Hideaway Tube for Small Pets',
    slug: 'crinkle-play-tunnel-hideaway-tube-small-pet',
    category: 'Toys & Play',
    petType: 'Small Pet',
    price: 330,
    originalPrice: 410,
    stock: 35,
    rating: 4.8,
    reviewsCount: 25,
    sku: 'PT-TOY-020',
    // Rabbit / guinea pig playing
    imageUrl: 'https://images.unsplash.com/photo-1535241749838-299277b6305f?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Collapsible 3-way burrowing tunnel with crackle lining sound that stimulates rabbits and guinea pigs.',
    description: 'Burrowing is the #1 instinctual behavior of wild lagomorphs. This lightweight collapsible tunnel features built-in crackling interior paper that rustles with every step, enticing energetic sprint laps and cozy naps.',
    keyBenefits: [
      '3 exit portals encourage high-speed zoomies and peek-a-boo play',
      'Crackling interior lining produces enticing sound cues',
      'Collapses completely flat in seconds with tie-strap for travel',
      'Tear-resistant polyester fabric wipes clean easily with a damp cloth',
    ],
    ingredients: 'Water-resistant Polyester Fabric, Spring Steel Internal Framing, Crinkle Paper Membrane.',
    usageGuide: 'Unsnap side ties to spring open. Place on playpen floor or room carpet.',
    weightSize: 'Length 80cm · Tunnel Diameter 25cm',
    brand: 'CritterJoy Gear',
    isFeatured: false,
  },

  // ─── 5. Grooming & Hygiene ───
  {
    title: 'Hypoallergenic Oatmeal & Aloe Vera Anti-Itch Dog Shampoo (500ml)',
    slug: 'oatmeal-aloe-vera-anti-itch-dog-shampoo-500ml',
    category: 'Grooming & Hygiene',
    petType: 'Dog',
    price: 490,
    originalPrice: 580,
    stock: 42,
    rating: 4.9,
    reviewsCount: 68,
    sku: 'PT-GRM-021',
    // Dog being groomed / bathed
    imageUrl: 'https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Tearless soap-free moisturizing wash formulated with colloidal oatmeal to relieve hot spots and sensitive skin.',
    description: 'Formulated specifically for canine pH (7.0), this soothing oatmeal wash deep-cleans dirt while protecting natural skin oils. Infused with organic aloe vera and sweet almond oil for a fresh coconut blossom scent.',
    keyBenefits: [
      'Instantly relieves itching caused by allergies and dry climate',
      '100% free from sulfates, parabens, dyes, and harsh alcohol',
      'Tearless gentle lather rinses clean without sticky residue',
      'Leaves fur fluffy, tangle-free, and smelling fresh for up to 14 days',
    ],
    ingredients: 'Deionized Water, Colloidal Oatmeal, Organic Aloe Vera Leaf Juice, Coconut-Derived Surfactants, Sweet Almond Oil, Vitamin E, Botanical Fragrance.',
    usageGuide: 'Wet coat thoroughly with lukewarm water. Massage shampoo from neck to tail, leave on for 5 minutes, rinse completely.',
    weightSize: '500ml Pump Bottle',
    brand: 'Paws & Tails Spa Care',
    isFeatured: true,
  },
  {
    title: 'Waterless Foaming Dry Bath Cleanse with Chamomile (200ml)',
    slug: 'waterless-foaming-dry-bath-cat-shampoo',
    category: 'Grooming & Hygiene',
    petType: 'Cat',
    price: 410,
    originalPrice: 490,
    stock: 38,
    rating: 4.9,
    reviewsCount: 43,
    sku: 'PT-GRM-022',
    // Cat being groomed / fluffy cat
    imageUrl: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=800&q=80',
    excerpt: 'No-rinse stress-free cleansing mousse that deodorizes feline coats without bathtub water panic.',
    description: 'Most cats dread water baths. This leave-in cleansing mousse traps dirt, dander, and saliva odors without requiring a single drop of rinse water. Gently brush through for a salon-fresh coat in 2 minutes.',
    keyBenefits: [
      'Zero water required — zero bath anxiety for your cat',
      'Neutralizes dander and pet odors naturally',
      'Safe for licking after brushing out',
      'Chamomile and lavender extract help calm nervous felines',
    ],
    ingredients: 'Purified Water, Chamomile Flower Extract, Lavender Oil, Oat Protein, Plant-Based Deodorizing Complex, Gentle Preservatives.',
    usageGuide: 'Pump foam onto hands, massage through cat\'s coat against fur grain, wipe with a dry towel, and brush gently.',
    weightSize: '200ml Foaming Pump',
    brand: 'Purrfect Delights',
    isFeatured: true,
  },
  {
    title: 'Self-Cleaning Stainless Steel Slicker Undercoat Brush',
    slug: 'self-cleaning-slicker-undercoat-brush',
    category: 'Grooming & Hygiene',
    petType: 'All Pets',
    price: 360,
    originalPrice: 450,
    stock: 55,
    rating: 5.0,
    reviewsCount: 89,
    sku: 'PT-GRM-023',
    // Pet brush / grooming tools
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80',
    excerpt: 'One-click retracting pin brush that effortlessly removes tangled knots, loose undercoat, and pet dander.',
    description: 'Tired of pulling stubborn fur clumps out of wire bristles with your fingers? With one click of the thumb release button, the stainless steel pins retract cleanly, allowing you to wipe away the whole fur pad in one smooth motion.',
    keyBenefits: [
      'One-button push ejects trapped fur instantly into the bin',
      'Fine bent wire pins with protective comfort tips will not scratch skin',
      'Reduces household shedding by up to 90% with regular weekly use',
      'Ergonomic non-slip rubberized handle prevents hand fatigue',
    ],
    ingredients: 'Stainless Steel Pins with Rounded Epoxy Tips, Impact ABS Body, Textured TPR Comfort Grip.',
    usageGuide: 'Gently brush in direction of fur growth. When pad is full, press top button to eject fur disc.',
    weightSize: 'Brush Head 10.5cm × 6.5cm',
    brand: 'Paws & Tails Spa Care',
    isFeatured: true,
  },
  {
    title: 'Dust-Free Lavender Clumping Bentonite Cat Litter (10L)',
    slug: 'dust-free-lavender-bentonite-cat-litter-10l',
    category: 'Grooming & Hygiene',
    petType: 'Cat',
    price: 480,
    originalPrice: 560,
    stock: 65,
    rating: 4.8,
    reviewsCount: 76,
    sku: 'PT-GRM-024',
    // Cat litter / cat in litter box area
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Fast-clumping natural sodium bentonite granules with activated carbon beads and subtle lavender scent.',
    description: 'Forms rock-hard scoopable clumps in under 3 seconds upon contact with liquid. 99.9% dust-free screening protects sensitive feline respiratory systems and keeps paw prints off hardwood floors.',
    keyBenefits: [
      'Rapid 3-second tight clumping locks in ammonia smell',
      '99.9% dust-free processing protects cats and human lungs',
      'Activated charcoal eliminates litter box odors for up to 30 days',
      'Gentle granular texture is soft on sensitive kitten paws',
    ],
    ingredients: '100% Natural Sodium Bentonite Clay, Activated Carbon Granules, Botanical Lavender Scent.',
    usageGuide: 'Fill clean litter box with 7-9cm depth. Scoop clumps daily and top up as needed.',
    weightSize: '10L (approx 8.0 kg) Bag',
    brand: 'Purrfect Delights',
    isFeatured: false,
  },
  {
    title: 'Professional Pet Nail Clipper with LED Light & Safety Guard',
    slug: 'pet-nail-clipper-led-light-safety-guard',
    category: 'Grooming & Hygiene',
    petType: 'All Pets',
    price: 280,
    originalPrice: 380,
    stock: 45,
    rating: 4.9,
    reviewsCount: 51,
    sku: 'PT-GRM-025',
    // Pet nail clipping / grooming tool close-up
    imageUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Ultra-sharp hardened stainless steel pet trimmer with built-in LED that illuminates the blood quick line.',
    description: 'Trimming your pet\'s nails doesn\'t have to be terrifying. Built-in ultra-bright LED illuminates delicate blood vessels in light-colored claws, preventing painful over-clipping and bleeding.',
    keyBenefits: [
      'Built-in LED clarifies the blood quick line to prevent injury',
      'Curved razor-sharp stainless steel blade cuts without crushing nail',
      'Transparent nail collection trap catches clippings for clean grooming',
      'Hidden mini nail file tucked into handle to smooth rough edges',
    ],
    ingredients: 'High-Density Hardened Stainless Steel Blade, ABS Ergonomic Shell, CR2032 Battery included.',
    usageGuide: 'Turn on LED switch, position nail at 45° angle safely away from pink bloodline, squeeze firmly to snip.',
    weightSize: 'Length 15cm · Suitable for Cats and Dogs',
    brand: 'Paws & Tails Spa Care',
    isFeatured: false,
  },
]
